### ISSUE TITLE
The best app to work with the clipboard!

### ISSUE THREAD

**Issue by sujaataarya** [quequotion/glippy#1]
Hi @quequotion!
The best app to work with the clipboard!
Loved it! I RECOMMEND TO ALL!
Thank you for your support of this package!
x86_64 Linux 4.8.13-1-ARCH and XFCE4.
Sincerely Sergey.
P.S.
Еven if the package is simply to exist, and is not updated, this is good!

**Comment by quequotion** [comment]
Thank you Sergey!
In truth, it's here mostly for the purpose of existing, but I also maintain a package for [Archlinux](https://github.com/quequotion/pantheon-bzr-qq/tree/master/EXTRAS/glippy-indicator) so I'll try to keep it in working order. Also accepting [contributions](https://github.com/quequotion/glippy/pull/2/commits/6c215f5d5d9cacc27e3cf48afe38e83febdac328)!
